language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - psql -c "CREATE USER testuser WITH PASSWORD 'testuser';" -U postgres
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"

notifications:
  email:
    on_failure: change
    on_success: change