language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:

before_deploy: "echo 'ready?'"

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

after_deploy: "echo 'Delploy FINISHED'"

notifications:
  email:
    on_failure: change
    on_success: change